- client/components/OperationListComponent.js
> Better nomenclature.

- README.md
> PFM ≠ Kresus.

- server/controllers/accesses.coffee
- server/controllers/accounts.coffee
- server/controllers/alerts.coffee
- server/controllers/banks.coffee
- server/controllers/categories.coffee
- server/controllers/helpers.coffee
- server/controllers/locale.coffee
- server/controllers/operations.coffee
- server/controllers/weboob.coffee
> https://github.com/bnjbvr/kresus/issues/69

- client/locales/en.js
- client/locales/fr.js
- client/main.js
- server/init.coffee
Also changed `by category by month` to `by category (monthly)`, and `par catégorie par mois` to `par catégorie (mensuel)`, because multiple dimensions are confusing.
> Improve English locale.

- static/css/style.css
This was supposed to be a drive-by in the previous pull request, but then I forgot about it.
> Increase margin between header and content.

- client/Models.js
- client/components/AccountList.js
- client/components/AmountWell.js
- client/components/BankList.js
- client/components/OperationList.js
- server/controllers/operations.coffee
- server/controllers/routes.coffee
Make proper file link fixes #121
Display account amount in side bar fixes #157
> Fix for #121 and #157

- server/lib/accounts-manager.coffee
- server/models/bankaccount.coffee
- weboob/py/connector.py
Hello,
This PR remplace https://github.com/bnjbvr/kresus/pull/164 thank to a comment of @ZeHiro.
Bye.
> retreive iban field from weboob

- client/Models.js
- client/components/OperationList.js
- client/locales/fr.js
- server/models/operation.coffee
Hi,
This is my rebased PR for the link between Kresus and the EDF app. I hope I forgot nothing.
> Add link between kresus and EDF

- client/components/OperationList.js
- client/css/style.css
- client/locales/fr.js
Hope this time it will fit. The branch is up to date with your incoming (if this is what you ment)
> Improve type/category selection

- client/components/SearchOperationList.js
Sorry for these open/close PR, I have some problems with git rebasing, merging branches etc...
> Improve search operations

- client/components/Charts.js
- client/main.js
Because it's correcter english.
> s/Graphics/Charts/ in the menu.

- client/components/SearchOperationList.js
According to https://github.com/bnjbvr/kresus/issues/142
> Set the "clear" button color to orange (= warning)

- client/components/NewBankForm.js
- client/components/SearchOperationList.js
- client/locales/fr.js
> Search pane UX

- client/components/SearchOperationList.js
- client/locales/fr.js
> Do not close search form on enter

- client/backend.js
- client/components/CustomBankField.js
- client/components/NewBankForm.js
- client/components/Settings.js
- client/locales/fr.js
- client/store.js
> Allow custom fields modification in edit access modal

- client/DefaultSettings.js
- client/components/Settings.js
- client/css/style.css
- client/locales/fr.js
- client/store.js
> Default bank account

- client/components/OperationList.js
- server/controllers/operations.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bnjbvr/kresus/299)
> Delete customLabel. Fixes #290

- client/backend.js
- client/components/AddOperationModal.js
- client/components/CategorySelectComponent.js
- client/components/DatePicker.js
- client/components/OperationList.js
- client/components/OperationTypeSelectComponent.js
- client/components/SelectableButtonComponent.js
- client/components/Settings.js
- client/components/ValidableInputDate.js
- client/components/ValidableInputNumber.js
- client/components/ValidableInputText.js
- client/locales/fr.js
- client/store.js
- server/controllers/accounts.js
- server/controllers/operations.js
- server/controllers/routes.js
- server/models/operation.js
fixes partially #166  : only deals with adding an operation. To do to close #166 : Add a "future operations" section. And remove future operations from balance  computation.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bnjbvr/kresus/297)
> [frontend] Allow to create operation for a given account

- client/components/OperationList.js
- client/store.js
- server/controllers/accounts.js
Do not trigger an error when the account deleted is the default account
Fix #302 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bnjbvr/kresus/304)
> Do not trigger error when deleting default account

- server/controllers/operations.js
Found it without opening a ticket. (req.params was ```undefined```)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bnjbvr/kresus/312)
> Fix bill recovery

- client/store.js
Fixes #306.
This works fine. But I am not sure there won't be a race condition in the dispatching of states.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bnjbvr/kresus/307)
> Deleting the last account of a bank, deletes the bank client side.

- .eslintrc.yml
- Makefile
- client/.eslintrc.yml
- client/components/AddOperationModal.js
- client/components/AmountWell.js
- client/components/Modal.js
- package.json
- scripts/lint.sh
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bnjbvr/kresus/321)
> Lint client

- client/components/SearchOperationList.js
> Fix wrong selected category when toggling on and off search panel

- client/css/style.css
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bnjbvr/kresus/329)
> Fix icons in operations manual creation

- shared/locales/fr.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bnjbvr/kresus/335)
> Improve translation

- client/components/settings/AddOperationModal.js
- client/store.js
- shared/locales/fr.js
> Use account title and emit State.opertions when creating an operation.

- client/components/duplicates/index.js
> Use type to filter to determine duplicates

- server/lib/accounts-manager.js
- server/lib/sources/mock.js
Fixes #209.
And improves fake operation generation : 
- Generation of duplicates with +/- 1 day
- Generation of twice the same operation on the same import
> Duplicates

- client/components/operations/search.js
- client/components/settings/add-operation-modal.js
- client/components/ui/date-picker.js
- shared/helpers.js
- shared/locales/en.js
- shared/locales/fr.js
- lint
- allow to set a minDate and a maxDate
- translate component
fixes #369
> Improve date-picker component:

- docker/Dockerfile-stable
- docker/entrypoint.sh
Problem : git pull/clone weboob didn't work because of self signed
certificate.
Solution : added attribute to git clone
Problem : weboob needed an extra package (mupdf-tools)
Solution : added package to apt-get install in Dockerfile
> Updated docker-file and entrypoint
